### ISSUE TITLE
 [119] FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by Futureganteng** [mediacms-io/mediacms#1002]
Hello, sorry i was not familiar with postgre

i get these error when i run the docker-compose up
db_1             | 2024-04-17 22:51:02.375 BST [119] FATAL:  role "root" does not exist
i logged on as root on the console

then i've logged on as admin on the website but
i get these message and the mediacms website goes down
celery_worker_1  | 2024-04-17 21:51:14,234 INFO reaped unknown pid 54 (terminated by SIGKILL)

**Comment by Nouri-redouane** [comment]
I got the same message, and i solved that by adding the following arguments to the "pg_isready" command in docker-compose.yaml file:
![image](https://github.com/mediacms-io/mediacms/assets/100516721/24ac125e-ada3-4d17-b71a-580dac299b75)
because the pg_isready command without -U is going to use the system user as the database user (in my case "root" because i executed docker-compose using sudo) 
i got that from:
https://stackoverflow.com/questions/70205657/postgres-docker-role-root-does-not-exist

**Comment by mgogoulos** [comment]
Pr was merged and this is fixed now!

**Comment by mgogoulos** [comment]
Pr was merged and this is fixed now!
