### ISSUE TITLE
Videos being encoded despite the DO_NOT_TRANSCODE_VIDEO = True

### ISSUE THREAD

**Issue by MarkovType** [mediacms-io/mediacms#1059]
**Describe the issue**

I edited the local_settings.py accordingly and set the DO_NOT_TRANSCODE_VIDEO flag to True. I also disabled all the encoding profiles from the mediacms django site administration, and rebooted the server several times. But still, when I upload a video, it shows "Media encoding is pending" on the video page. The encoding then fails, and I cannot see the video.

**To Reproduce**
Steps to reproduce the issue:
1. Add DO_NOT_TRANSCODE_VIDEO = True flag to the local_settings.py and restart server
2. Upload one video
3. Media encoding is pending

**Expected behavior**
The videos should not be transcoded and the viewer should get the original video file.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation method: Single server install
 - Firefox

**Comment by MarkovType** [comment]
Does anyone know where can I get the logs for mediacms ?

**Comment by habibulilalbaab** [comment]
you can set DO_NOT_TRANSCODE_VIDEO in cms/settings.py

**Comment by MarkovType** [comment]
> you can set DO_NOT_TRANSCODE_VIDEO in cms/settings.py

Well it worked, thanks.
What's the point of local_settings.py then ? Why this single parameter didn't apply ?

**Comment by mgogoulos** [comment]
hi @MarkovType , the idea of a file cms/local_settings.py is that you have extra settings that override the ones in cms/settings.py and you don't have to commit this to the code repository, since it might contain secrets as well - there are better ways to achieve this by reading OS variables but that is what we have now. 

so if you create a file cms/local_settings.py and place `DO_NOT_TRANSCODE_VIDEO = True` it should the same as placing it in cms/settings.py 

As far as the logs, they are found on the logs folder , if you installed with the single server install, that would be /home/mediacms/mediacms.io/logs

**Comment by MarkovType** [comment]
Alright, I get it. 
Before that I had the DO NOT TRANSCODE flag set to False in settings.py, which is why setting it to True in local_settings.py didn't change anything.

Thanks for your answer
