### ISSUE TITLE
Cannot access Django admin with new superuser account.

### ISSUE THREAD

**Issue by Dan1ell** [mediacms-io/mediacms#135]
When logged in as a superuser that I have created, I cannot enter the Django admin. 
I can see the 3 management options in the left sidebar and can enter them.
I can also see the link to the Django admin under my logo, but cannot access the Django admin. 

`You are authenticated as Dan1ell, but are not authorized to access this page. Would you like to login to a different account?`

I can only enter the Django admin with the original admin account created during installation. Other superuser accounts can't be used for the Django admin. This is a problem because now only 1 account truly has full access to the site.

**Comment by mgogoulos** [comment]
This is handled with https://github.com/mediacms-io/mediacms/pull/156

In order to access the Django administration you need both is_superuser and is_staff. The former was exposed to the admin dashboard, inside the User information, but the latter wasn't. 
So you must have created a user account, grant them is_superuser access but without the is_staff you cannot enter the admin dashboard.

**Comment by Dan1ell** [comment]
It's working, thank you!
