### ISSUE TITLE
Cannot verify email of automatically created admin user

### ISSUE THREAD

**Issue by Dan1ell** [mediacms-io/mediacms#136]
I want to change the email settings to require email verification. However, when I do that, I cant log in with the auto-generated admin anymore because it was never verified. 

I resend the verification code for it, the verification email arrives, I verify, I see the message ‘You have confirmed’ and am automatically logged in as the admin. But when I check ‘Manage users’ in the left column, the admin account is still not marked verified.

I can’t just switch to using a different superuser account instead of the admin account because of issue #135 where other superusers I make, cannot access the Django admin. 

(This one is kind of important because if I can’t set email verification to mandatory, I have to delay launching the site until that’s fixed. I hope this one (or at least #135) can get resolved quickly)

**Comment by mgogoulos** [comment]
Since #135 is fixed now, I'll close this

For what is worth, if you set 

```
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
```
on settings.py/local_settings.py, existing accounts needs to be verified otherwise they are considered as unverified. 
If email verification doesn't work for an account, you can still verify it through the Admin dashboard by making verified as True on http://site/admin/account/emailaddress/ , and also through the console (python manage.py shell)

```
from users.models import User                                                                                                                                                                              
user = User.objects.get(username='user')                                                                                                                                                                      
user.email_is_verified = True
user.save()                                                                                                                                                                                 
```

Apparently if you set the email settings it should all be handled through email but this could be used as a last resort in some cases as the one you describe. 

Thanks
