### ISSUE TITLE
[Feature] LDAP/AD support for authentication

### ISSUE THREAD

**Issue by distantbit** [mediacms-io/mediacms#195]
Let users choose their domain account for logging in and automagically create users with given user profile in LDAP directory.

E.g. https://django-auth-ldap.readthedocs.io/en/latest/ can be used for that.

**Comment by mgogoulos** [comment]
Won't be added any time soon on the open source project - closing

**Comment by MairusuPawa** [comment]
Oh

**Comment by TheITguy21** [comment]
Hi ! I must admit LDAP/AD support would be awesome. As most of self-hosted products, they're usually intended to be used in a network (school, small team etc) based on LDAP/AD. It's too bad MediaCMS can't rely on LDAP users to sign in :)
Besides that, MediaCMS is awesome ❤

**Comment by TheITguy21** [comment]
(A couple days later..)
Finally, I managed to set up LDAP sync using `django-ldad-sync` (to pre-create accounts in  MediaCMS so users exist and can be mentioned even if they never logged in MediaCMA 😉) and LDAP authentication backend `django-auth-ldap` so users can log in to MediaCMS with their Active Directory account.
If someone here is trying to achieve the same thing, just IM, I can help 🙂
I was too lazy to publish a documentation somewhere online (I'm not even sure about the proper way to do it here on github 😐), but I can share my personal documentation if someone needs it.
Cheers

**Comment by TheITguy21** [comment]
# LDAP/AD support for authentication #
Ok people asked me how I did it, I hope it'll be ok I post it here 😅

My environment : 
`Description:    Debian GNU/Linux 11 (bullseye)`
`Release:        11`
`Codename:       bullseye`
LDAP source : Active Directory Domain

## Disclaimer ##
- **The content of my personal documentation/notes is posted as is without guarantee**, it took me hours to gather and understand what I had to do to reach my goal, I didn't even know anything about Django nor Python when I started, so maybe what I did is not purely elegant. Anyway, it works 😅

- I have no idea if using `django-ldad-sync` and `django-auth-ldap`, or even posting this here is "license compliant". So if you don't either, use this for personal use in you lab or do what you have to do so you don't break any licensing rules. Fell free to give me feedback about it, I always did my stuff for myself at home and never had to worry or learn about licensing so far..

**Please review the whole thing before diving in, don't copy-paste as an idiot and try to understand first what you're doing** 🙂 Also refer to the documentation links related to `django-ldad-sync` and `django-auth-ldap` packages.

**⚠WARNING:I won't be able to provide any support if you mess up, so as always : DO MAKE BACKUPS before anything.**
Good luck !

# Here we go #

✅If I didn't mess up, you can just copy-paste my code blocks in your bash. You'll just have to manually edit some variables later at some point in the process (you'll be told)

## Part 1 - Sync/Pre-create users from LDAP ##
### _The purpose of this part is to prefetch LDAP Users & Groups to MediaCMS_ ###

🌐 [https://pypi.org/project/django-ldap-sync/ ](https://pypi.org/project/django-ldap-sync/ )
📚 [https://django-ldap-sync.readthedocs.io/en/latest/](https://django-ldap-sync.readthedocs.io/en/latest/) 

- Install prerequisites
```shell
sudo apt install -y \
  libldap2-dev \
  libsasl2-dev \
  python3-dev
``` 

- Install `django-ldad-sync` in **MediaCMS** Python virtual environment
```shell
# Enter MediaCMS Python virtual environment
cd /home/mediacms.io
virtualenv . --python=python3
source /home/mediacms.io/bin/activate
cd mediacms
# Install Python packages
pip install python-ldap
pip install django-ldap-sync
# Exit MediaCMS Python virtual environment
deactivate
# Set permissions
sudo chown -R www-data. /home/mediacms.io/
``` 
ℹ`django-ldap-sync` package is installed in `/home/mediacms.io/lib/python3.9/site-packages/ldap_sync`

- Enter and store the LDAP password in a variable
⚠Don't use special characters in password (`$` in particular) to avoid escaping problems in the variable
```shell
read -s -p "Enter password for the LDAP connection :" LdapPassword
``` 

- Add "`ldap_sync`" to `INSTALLED_APPS` in `/home/mediacms.io/mediacms/cms/settings.py`
```shell
if [ -z "$(grep -Eo '"ldap_sync",' /home/mediacms.io/mediacms/cms/settings.py)" ]; then
    sudo sed -i -E 's/(INSTALLED_APPS = .+)/\1\n    "ldap_sync",/' /home/mediacms.io/mediacms/cms/settings.py
fi
``` 

- Update configuration file `/home/mediacms.io/mediacms/cms/settings.py`
📖 [https://django-ldap-sync.readthedocs.io/en/latest/settings.html ](https://django-ldap-sync.readthedocs.io/en/latest/settings.html )
```shell
sudo tee -a /home/mediacms.io/mediacms/cms/settings.py >/dev/null << EOF



##########
#
# LDAP->Local Users/Groups sync
#
#####
# Connection settings
LDAP_SYNC_URI = "ldap://ldap.yourdomain.corp:389"
LDAP_SYNC_BASE = "OU=USERS,DC=yourdomain,DC=corp"
LDAP_SYNC_BASE_USER = "CN=SVC_LDAP_MediaCMS,OU=ACCOUNTS,DC=yourdomain,DC=corp"
LDAP_SYNC_BASE_PASS = "${LdapPassword}"

# An LDAP filter to further refine the user accounts to synchronize
# Here, we'll look for not-disabled accounts, recursively members of group GRP_MediaCMS_Users
LDAP_SYNC_USER_FILTER = "(&(objectClass=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf:1.2.840.113556.1.4.1941:=CN=GRP_MediaCMS_Users,OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp))"
 
# A dictionary mapping "LDAP attributes" to "User profile attributes".
# New users will be created with this data populated, and existing users will be updated as necessary
LDAP_SYNC_USER_ATTRIBUTES = {
    "sAMAccountName": "username",
    "givenName": "first_name",
    "sn": "last_name",
    "mail": "email",
    "description": "description",
    "displayName": "name",
    "title": "title",
    "l": "location",
}
# An optional field on the synchronized User model to use as the unique key for each user.
# If not specified, the User model’s "USERNAME_FIELD" will be used.
# If specified, the field must be included in "LDAP_SYNC_USER_ATTRIBUTES"
LDAP_SYNC_USERNAME_FIELD = "username"

# An LDAP filter string to further refine the groups to synchronize.
# This should be a string specifying any valid filter string
#LDAP_SYNC_GROUP_FILTER = "(&(objectclass=group))"
LDAP_SYNC_GROUP_FILTER = "(&(objectclass=group)(CN=GRP_MediaCMS_Users,OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp))"

# A dictionary mapping "LDAP field names" to "Group attributes".
# New groups will be created with this data populated, and existing groups will be updated as necessary.
# The mapping must at least contain a field with the value of "name" to specify the group’s name
LDAP_SYNC_GROUP_ATTRIBUTES = {
    "cn": "name",
}

# Add a cron to Celery to sync LDAP users ->django periodically
# Problem - couldn't make this work for now :-(
#   The task is invoked (cf log /home/mediacms.io/mediacms/logs/beatcelery_beat.log)
#   but it's not run by Celery workers.
#   I even tries to set the task directly within /home/mediacms.io/mediacms/files/tasks.py, no success..
# Workaround->Use normal cron at OS level to process LDAP Sync
# Here's the task I've been trying to set without success:
#SyncSchedule = {
#    # Sync LDAP every hour
#    "synchronize_local_users": {
#        "task": "ldap_sync.tasks.syncldap",
#        "schedule": crontab(minute=0, hour="*"),
#    },
#}
#CELERY_BEAT_SCHEDULE.update(SyncSchedule)
EOF
``` 
ToDo👉🏻**YOU NEED TO CUSTOMIZE THE FOLLOWING VARIABLES** according to your environment:
`LDAP_SYNC_URI`
`LDAP_SYNC_BASE`
`LDAP_SYNC_BASE_USER`
`LDAP_SYNC_USER_FILTER`
`LDAP_SYNC_GROUP_FILTER`

- ⚠Pre-fix the error you're about to get later when syncing
![image](https://github.com/mediacms-io/mediacms/assets/127893834/8b618efa-4192-4297-81b9-81082aa95381)
📄 [https://stackoverflow.com/questions/19877064/typeerror-unsupported-operand-types-for-dict-keys-and-list](https://stackoverflow.com/questions/19877064/typeerror-unsupported-operand-types-for-dict-keys-and-list)
```shell
sudo sed -i -E '/user_attributes = /{s/(self\.settings\.USER_ATTRIBUTES)\.keys\(\)/list(\1)/}' /home/mediacms.io/lib/python3.9/site-packages/ldap_sync/sync.py
``` 

- Launch a first LDAP sync manually
```shell
/home/mediacms.io/bin/python /home/mediacms.io/mediacms/manage.py syncldap
``` 

- Create crontab to automate LDAP sync
⚠**First, make sure crontab file exists for `root` !
Run `crontab -e` once to make sure before pasting/running this code in bash** 👇🏻
```shell
# Add LDAP sync crontab job
if [ -z "$(sudo crontab -l | grep syncldap)" ]; then
    sudo crontab -l > /tmp/crons &&
    sudo echo -e "\n# Sync LDAP users\n0 * * * * /home/mediacms.io/bin/python /home/mediacms.io/mediacms/manage.py syncldap" >> /tmp/crons &&
    sudo crontab /tmp/crons &&
    sudo rm /tmp/crons &&
    sudo service cron reload
fi
``` 


## Part 2 - Install LDAP authentication backend ##
### _The purpose of this part is to let LDAP Users to authenticate/Log In to MediaCMS_ ###

📖 [**https://github.com/shalomz/HowTo/blob/master/Django%20with%20AD%20(django-auth-ldap).md**](https://github.com/shalomz/HowTo/blob/master/Django%20with%20AD%20(django-auth-ldap).md)

🌐 [https://pypi.org/project/django-auth-ldap/](https://pypi.org/project/django-auth-ldap/ )
📚 [https://django-auth-ldap.readthedocs.io/en/latest/](https://django-auth-ldap.readthedocs.io/en/latest/) 
📖 [https://coderbook.com/@marcus/how-to-add-ldap-and-active-directory-authentication-to-django/](https://coderbook.com/@marcus/how-to-add-ldap-and-active-directory-authentication-to-django/) 

- Install prerequisites
```shell
sudo apt install -y \
  libldap2-dev \
  libsasl2-dev \
  python3-dev # python-dev = python-dev-is-python2 or 3 is OLD
``` 

- Install `django-auth-ldap` in **MediaCMS** Python virtual environment
```shell
# Enter MediaCMS Python virtual environment
cd /home/mediacms.io
virtualenv . --python=python3
source /home/mediacms.io/bin/activate
cd mediacms
# Install Python packages
pip install python-ldap
pip install django-auth-ldap
# Exit MediaCMS Python virtual environment
deactivate
# Set permissions
sudo chown -R www-data. /home/mediacms.io/
``` 

ℹ`django-auth-ldap` package is installed in `/home/mediacms.io/lib/python3.9/site-packages/django_auth_ldap`

- Enter and store the LDAP password in a variable
⚠Don't use special characters in password (`$` in particular) to avoid escaping problems in the variable
```shell
read -s -p "Enter password for the LDAP connection :" LdapPassword
``` 

- Update configuration file` /home/mediacms.io/mediacms/cms/settings.py`
📖 [https://django-auth-ldap.readthedocs.io/en/latest/reference.html#settings](https://django-auth-ldap.readthedocs.io/en/latest/reference.html#settings) 
```shell
sudo tee -a /home/mediacms.io/mediacms/cms/settings.py >/dev/null << EOF

##########
#
# LDAP Authentication Backend
#
#####
try:
    import ldap 
    from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion, NestedActiveDirectoryGroupType

    # Baseline configuration
    AUTH_LDAP_SERVER_URI = "ldap://ldap.yourdomain.corp:389"
    AUTH_LDAP_BIND_DN = "CN=SVC_LDAP_MediaCMS,OU=ACCOUNTS,DC=yourdomain,DC=corp"
    AUTH_LDAP_BIND_PASSWORD = "${LdapPassword}"
    AUTH_LDAP_START_TLS = True
    AUTH_LDAP_CONNECTION_OPTIONS = { ldap.OPT_DEBUG_LEVEL: 1, ldap.OPT_REFERRALS: 0, }

    # Set up the basic user/group search objects and types
    #AUTH_LDAP_USER_SEARCH = LDAPSearch("OU=USERS,DC=yourdomain,DC=corp", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
    AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
        LDAPSearch("OU=USERS,DC=yourdomain,DC=corp",ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"),
        LDAPSearch("OU=USERS,DC=yourdomain,DC=corp", ldap.SCOPE_SUBTREE, "(mail=%(user)s)"),
    )
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp", ldap.SCOPE_SUBTREE, "(objectClass=group)")
    AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()

    # Simple group restrictions
    #AUTH_LDAP_REQUIRE_GROUP = "cn=enabled,ou=django,ou=groups,dc=example,dc=com"
    #AUTH_LDAP_DENY_GROUP = "cn=disabled,ou=django,ou=groups,dc=example,dc=com"

    # Prevent the creation of new users during authentication.
    # Any users not already in the Django user database will not be able to login
    AUTH_LDAP_NO_NEW_USERS = False

    # Populate the Django user from the LDAP directory using
    # mapping from "User profile attributes" to "LDAP attribute"
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "sAMAccountName",
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
        "description": "description",
        "name": "displayName",
        "title": "title",
        "location": "l",
    }
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_active": "CN=GRP_MediaCMS_Users,OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp",
        "is_staff": [
            "CN=GRP_MediaCMS_UsersStaff,OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp",
        ],
        "is_superuser": "CN=GRP_MediaCMS_UsersAdmins,OU=MediaCMS,OU=GROUPS,DC=yourdomain,DC=corp",
    }

    # The field on the user model used to query the authenticating user in the database.
    # If unset, uses the value of USERNAME_FIELD of the model class.
    # When set, the value used to query is obtained through the AUTH_LDAP_USER_ATTR_MAP bellow
    AUTH_LDAP_USER_QUERY_FIELD = "username"

    # This is the default, but I like to be explicit
    AUTH_LDAP_ALWAYS_UPDATE_USER = True

    # If AUTH_LDAP_MIRROR_GROUPS is True, then every time a user logs in, LDAPBackend will update the database with the user’s LDAP groups.
    # Any group that doesn’t exist will be created and the user’s Django group membership will be updated to exactly match their LDAP group membership
    # Can be 'True' or an exclusive list ["Group1", "Group2, ..]
    #AUTH_LDAP_MIRROR_GROUPS = True
    AUTH_LDAP_MIRROR_GROUPS = ["GRP_MediaCMS_AdvancedUsers", "GRP_MediaCMS_Editors", "GRP_MediaCMS_Managers"]

    # Use LDAP group membership to calculate group permissions
    AUTH_LDAP_FIND_GROUP_PERMS = True

    # Cache distinguished names and group memberships for an hour to minimize LDAP traffic
    AUTH_LDAP_CACHE_GROUPS = True
    AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

    # Keep ModelBackend around for per-user permissions and maybe a local superuser
    AUTHENTICATION_BACKENDS = (
        "django_auth_ldap.backend.LDAPBackend",
        "django.contrib.auth.backends.ModelBackend",
        "allauth.account.auth_backends.AuthenticationBackend"
    )
except ImportError:
    pass
EOF
``` 
ToDo👉🏻Again, **YOU NEED TO CUSTOMIZE THE FOLLOWING VARIABLES** according to your environment:
`AUTH_LDAP_SERVER_URI`
`AUTH_LDAP_BIND_DN`
`AUTH_LDAP_USER_SEARCH`
`AUTH_LDAP_GROUP_SEARCH`
`AUTH_LDAP_USER_FLAGS_BY_GROUP`

ℹ**About roles in django**
`is_active` : Boolean. Marks this user account as active. We recommend that you set this flag to False instead of deleting accounts. That way, if your applications have any foreign keys to users, the foreign keys won’t break. This doesn’t necessarily control whether or not the user can log in. Authentication backends aren’t required to check for the is_active flag but the default backend (ModelBackend) and the RemoteUserBackend do.
`is_staff` : Boolean. Allows this user to access the admin site.
`is_superuser` : Boolean. Treats this user as having all permissions without assigning any permission to it in particular.
📖 [https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#custom-users-and-django-contrib-admin](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#custom-users-and-django-contrib-admin)


## Part 3 - Enable LDAP logging ##
### _The purpose of this step is to set a dedicated log for anything related to LDAP sync & connections_ ###

- Edit/Set the `LOGGING` block in `/home/mediacms.io/mediacms/cms/settings.py` to enable/customize logging outputs
📚 [https://docs.djangoproject.com/en/5.0/topics/logging/](https://docs.djangoproject.com/en/5.0/topics/logging/) 
```shell
 ...
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": error_filename,
        },
        "file_auth_ldap": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGS_DIR, "auth_ldap.log"),
        },
        "file_ldap_sync": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGS_DIR, "ldap_sync.log"),
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "ERROR",
            "propagate": True,
        },
        "django_auth_ldap": {
            "handlers": ["file_auth_ldap"],
            "level": "INFO",
            "propagate": True,
        },
        "ldap_sync": {
            "handlers": ["file_ldap_sync"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
 ...
``` 
ℹ The events will be logged in the following files:
- LDAP Sync -> `/home/mediacms.io/mediacms/logs/ldap_sync.log`
- LDAP Authentication -> `/home/mediacms.io/mediacms/logs/auth_ldap.log`
