### ISSUE TITLE
[Feature] Hardware Acceleration Encoding

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#21]
Can you please let me know if Nvidia hardware acceleration encoding is supported? 
If so, how can it be implemented to available in the native setup, and/or future releases through docker

**Comment by mgogoulos** [comment]
please bring this to the discussions section and close this issue. 

Since ffmpeg is handling all video transcodings, I believe if you compile ffmpeg to support your GPU it will work, a good starter seems https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/ . Would be interesting to hear how this goes if you try it!

**Comment by mprajescu** [comment]
I was thinking about the same thing, however, I would wait a bit until I can deploy it directly on a physical server or maybe when docker version is available to pass through the GPU, and then will test more.

**Comment by dungtranhoang** [comment]
Hi @mprajescu , how did u archive this with using GPU to encode? Thank you! I would like to try too!

**Comment by mprajescu** [comment]
I dropped the mediacms app and used a different solution at that time (can't remember which one because it was 5 years ago!) The reason why I dropped it was because there was no SSO support and didn't had suport in docker for GPU passthrough and would not put it on bare hardware to waste resources.
