### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by NerdDoc** [mediacms-io/mediacms#44]
Hi! I got this error in errors log and have no icons.
Here is error message -  The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/materialicons/v70/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2. (Reason: CORS request did not succeed).

**Comment by mgogoulos** [comment]
Hi, this is strange, wonder how it has happened (cannot replicate). You can set the option

```
LOAD_FROM_CDN = True
```

to False, on cms/local_settings.py, and then restart the service

```
sudo systemctl restart mediacms
```

so that everything loads from the local files directory (/static) and no content is loaded from CDNs, but I'd like to see if we can replicate and add a fix

thanks

**Comment by NerdDoc** [comment]
Yes, all is ok. About my use case - mediacms is installed in separate lxc container- ubuntu18.04. I did nothing with mediacms, just upload several files. I will try to reproduce this problem, and then will left comment here.

**Comment by NerdDoc** [comment]
I think this problem was connected with a lot of requests from my side.
