### ISSUE TITLE
tags will not show up other than English

### ISSUE THREAD

**Issue by ttkrpink** [mediacms-io/mediacms#464]
**Describe the issue**
If you add a category in Chinese or Arabic, it will be displayed fine. 
If you add a new tag in Chinese to the admin page, it will not be displayed.
If you add a new tag in Arabic to the admin page, it will crash the server.

**To Reproduce**
Steps to reproduce the issue:
1. Go to the Django admin page
2. Add a new tag. If it's in English, everything works fine. If it's in Chinese, it will not be displayed. As shown in the second screen capture, the first entry is not shown. If you input Arabic, it will crash the server error 500
3. If you add a new tag in the Media Edit page, it will not be displayed.

**Expected behavior**
It should be displayed as the category page displayed just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/2522889/174019228-0ee6355b-881c-4b37-aea2-80afc3213823.png)
![image](https://user-images.githubusercontent.com/2522889/174017907-84a6b05d-dc03-4e89-836a-23df64658fd4.png)
![image](https://user-images.githubusercontent.com/2522889/174019360-cb02f204-3823-450a-bfbe-4afc813c4b53.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Installation method: Docker install
 - Browser, Chrome

**Comment by mgogoulos** [comment]
I've created https://github.com/mediacms-io/mediacms/pull/801 and will merge it now that fixes this problem. 

Until now tags were allowed to contain English characters and letters only, while now all characters are allowed (so  you can create tags in Russian/Chinese etc). Special characters as #, ( etc are still stripped.

Also the 500 error on Django admin is happening because when you save the tag it gets stripped out of the blacklisted characters and what remains is an empty tag, that gets to be added twice. This cannot happen when you create a tag by Editing a media
