### ISSUE TITLE
Docker Hub only serves the "latest"-image

### ISSUE THREAD

**Issue by Husky110** [mediacms-io/mediacms#518]
**Describe the feature you'd like**
I would like to propose that everytime a new release-tag is made in GitHub it is also released on dockerhub. The current version breaks all videos, so I am not even able to revert to an older version to get my videos running. So the best practice for a new release would be that all releases are beeing uploaded to docker hub whereas the newest one also replaces the "latest" tag, but keeping all the old versions alive and not breaking anything. The very idea of docker is to let the user decide which version to run on...

**Describe alternatives you've considered**
Not seeing my video beeing unable to load? I don't know what to write here... :)

**Additional context**
None

**Comment by mgogoulos** [comment]
Great suggestion, just needs a plan and we can execute it. Can you prepare some instructions for the workflow?

**Comment by Husky110** [comment]
To be honest - I have no freakin' clue how that stuff works... :D  
But out of my head I would suggest the following:  

- Do coding and release a new tag
- Send an image to dockerhub with the new release-tag
- update the current "latest"-image to use the new release-tag
- leave the older tags alone

Maybe you can contact Drakkan at this repo: https://github.com/drakkan/sftpgo he is running and maintaining an SFTP-server and I know from first-hand experience that he answers his tickets. So maybe you guys can link together and help each other out. :)

**Comment by mgogoulos** [comment]
thanks for the suggestion, i'll let this issue open and will try to find some time to implement

**Comment by Adito5393** [comment]
Keep in mind the latest DockerHub news: [Docker is deleting Open Source organisations](https://blog.alexellis.io/docker-is-deleting-open-source-images/). Maybe release the images to the GitHub repository?

**Comment by Adito5393** [comment]
Great to hear you have a paid subscription. I'd like to contribute by adding GitHub actions for automatically releasing Docker images with version tags. To avoid vendor lock-in with GitHub Actions YAML format, I'll write the build commands in a Bash file instead. This is a common practice with CI/CD tools. I'll ping you again when the PR draft is ready for review.

**Comment by mgogoulos** [comment]
Hi @Adito5393 , just saw the other PR, looks great! Will try to find some time to test it before I merge it. 

And yes, definitely some help is needed. What you suggest is important, please go ahead and create a PR when you have the capacity. And as you probably have seen there's room for good optimizations, eg 

* removing a number of variables (that were introduced mostly to facilitate Django migrations, but serve no other purpose any more)
* even removing some of the docker compose files, or better using overrides, so that there is not that big number anymore (that makes testing them very hard)
* suggestions on whether DB and media_files should be defined ona different way
* even the Dockerfiles for backend/frontend need to be updated
* https://github.com/mediacms-io/mediacms/issues/709 but I'm sure there are other tickets as well related with Docker

Thanks and regards
